### ISSUE TITLE
AttributeError: 'Dataset' object has no attribute 'value'

### ISSUE THREAD

**Issue by szm-R** [KamitaniLab/GenericObjectDecoding#19]
Hi,

Following the instruction in the ReadMe file, I downloaded the .h5 files from [figshare ](https://figshare.com/articles/Generic_Object_Decoding/7387130) and put in the "data" directory in code/python and then tried to run the analysis_FeaturePrediction.py script. This is what it gives me:
----------------------------------------
Loading data
Traceback (most recent call last):
  File "C:/PhD/Courses/Biosignal processing/Project/PythonProject/analysis_FeaturePrediction.py", line 306, in <module>
    main()
  File "C:/PhD/Courses/Biosignal processing/Project/PythonProject/analysis_FeaturePrediction.py", line 67, in main
    data_all[sbj] = bdpy.BData(subjects[sbj][0])
  File "C:\PhD\Courses\Biosignal processing\Project\PythonProject\venv\lib\site-packages\bdpy\bdata\bdata.py", line 79, in __init__
    self.load(file_name, file_type)
  File "C:\PhD\Courses\Biosignal processing\Project\PythonProject\venv\lib\site-packages\bdpy\bdata\bdata.py", line 708, in load
    self.__load_h5(load_filename)
  File "C:\PhD\Courses\Biosignal processing\Project\PythonProject\venv\lib\site-packages\bdpy\bdata\bdata.py", line 874, in __load_h5
    if isinstance(v.value, np.ndarray):
AttributeError: 'Dataset' object has no attribute 'value'

Process finished with exit code 1

I tried to debug the code but couldn't get much out of it and would appreciate any help greatly.

Thank you.

**Comment by szm-R** [comment]
I downloaded the .h5 files again and it worked! I don't know what was wrong with the previous downloads...
