### ISSUE TITLE
KeyError: "Unable to open object (Object 'metadata' doesn't exist)"

### ISSUE THREAD

**Issue by varSwift** [KamitaniLab/GenericObjectDecoding#3]
Excuse me,when I run the file "analysis_FeaturePrediction.py",There was an error.as follows:
`
----------------------------------------
Loading data
Traceback (most recent call last):
 File "analysis_FeaturePrediction.py", line 306, in <module>
  main()
File "analysis_FeaturePrediction.py", line 74, in main
data_feature = bdpy.BData(image_feature)
  File "/home/zjt2/.local/lib/python2.7/site-packages/bdpy/bdata/bdata.py", line 72, in __init__
self.load(file_name, file_type)
 File "/home/zjt2/.local/lib/python2.7/site-packages/bdpy/bdata/bdata.py", line 558, in load
 self.__load_h5(load_filename)
File "/home/zjt2/.local/lib/python2.7/site-packages/bdpy/bdata/bdata.py", line 700, in __load_h5
 md_keys = dat["metadata"]['key'][:].tolist()
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/_objects.c:2846)
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/_objects.c:2804)
File "/opt/anaconda/envs/python2/lib/python2.7/site-packages/h5py/_hl/group.py", line 169, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/_objects.c:2846)
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/_objects.c:2804)
File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/h5o.c:3740)

KeyError: "Unable to open object (Object 'metadata' doesn't exist)"

`
can you tell me some reasons?

**Comment by ShuntaroAoki** [comment]
The error is due to file format changes in our lab. I uploaded a data file (`ImageFeatures.h5`) which is compatible to the latest Python code. Please download it from http://brainliner.jp/data/brainliner/Generic_Object_Decoding, put it in your data directory, and try the script again.

**Comment by varSwift** [comment]
Thanks for your reply, I will try the script again.thanks~

**Comment by zara6697** [comment]
> 
> 
> The error is due to file format changes in our lab. I uploaded a data file (`ImageFeatures.h5`) which is compatible to the latest Python code. Please download it from http://brainliner.jp/data/brainliner/Generic_Object_Decoding, put it in your data directory, and try the script again.

Deal all,
I download the new file of "ImageFeatures.h5" but the error also exists ("Unable to open object (object 'metadata' doesn't exist)"). I use python 2.7 in spyder environment.

**Comment by ajayp1** [comment]
hello, i'm trying to load subject data (Subject1.h5) and I'm getting the same. error. Can you reupload the subject data in the compatible format as well? Thanks!

**Comment by mitsuaki** [comment]
I have confirmed that the data file (Subject1.h5) is in compatible format.　
Please make sure that the data path and file size is correct.
The file size of the Subject1.h5 is about 120MB, so if not, please download it again.
